### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mhosman** [alexshakura/mat-ngx-wig#1]
ERROR in node_modules/mat-ngx-wig/src/mat-ngx-wig/mat-ngx-wig.component.d.ts(7,22): error TS2720: Class 'MatNgxWigComponent' incorrectly implements class 'MatFormFieldControl<string>'. Did you mean to extend 'MatFormFieldControl<string>' and inherit its members as a subclass?
  Property 'shouldLabelFloat' is missing in type 'MatNgxWigComponent'.

**Comment by alexey-shakura** [comment]
There was a change in `MatFormFieldControl` from version 6. You can try latest version which supports `angular-material@7.0.0` and higher
